# Node.js 20.16.0 이미지 사용
FROM node:20.16.0

# 작업 디렉토리 설정
WORKDIR /app

# package.json 및 package-lock.json 복사
COPY ./package*.json ./

# 의존성 설치
RUN npm install

# 소스 코드 복사
COPY . . 

# Next.js 빌드
RUN npm run build

# 애플리케이션 포트 설정 (Next.js 기본 포트)
EXPOSE 3000

# 애플리케이션 실행 (프로덕션 모드)
CMD ["npm", "run", "start"]
